GOOD_MOCK_SERVER_NO_AUTH = "http://localhost:8086/ga4gh/drs/v1"
GOOD_MOCK_SERVER_BASIC= "http://localhost:8087/ga4gh/drs/v1"
GOOD_MOCK_SERVER_BEARER = "http://localhost:8088/ga4gh/drs/v1"
GOOD_MOCK_SERVER_PASSPORT = "http://localhost:8089/ga4gh/drs/v1"
SERVICE_INFO_URL = "/service-info"